# Generated by Django 2.2.28 on 2022-12-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameDisease_VN', models.CharField(max_length=100)),
                ('NameDisease_ENG', models.CharField(max_length=100)),
                ('Symptom', models.CharField(max_length=2000)),
                ('Pathogens', models.CharField(max_length=2000)),
                ('Treatment', models.CharField(max_length=2000)),
            ],
        ),
    ]
