# Generated by Django 2.2.28 on 2022-12-06 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField()),
                ('PredictResult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.Diseases')),
            ],
        ),
    ]
