# Generated by Django 2.2.28 on 2022-12-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_predict'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict',
            name='Image',
            field=models.CharField(default='abcd', max_length=1000),
            preserve_default=False,
        ),
    ]
