# Generated by Django 2.2.28 on 2022-12-06 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_predict_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predict',
            name='DateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
