# Generated by Django 2.2.28 on 2022-12-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_predict_confident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predict',
            name='Image',
            field=models.URLField(max_length=1000),
        ),
    ]
